#!/usr/bin/env bash
# Transfers file from our client to a server
#	$4 - The path to the private_key to use for authentication
#	$1 - The path to the file
#	$3 - Server username
#	$2 - hostname/ip address of remote server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
