#!/usr/bin/env bash
# Configures an Nginx server to have a custom 404 page that contains the string
# Uses sed command to edit the /etc/nginx/sites-available/default file
# Ceci n'est pas une page

touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
fil='/etc/nginx/sites-available/default'
add="
        error_page 404 /404.html;
        location /404 {
                root /etc/nginx/html
                internal;
        }"
sudo echo "$add" > tmp2
sudo sed -i "/\t}/r tmp2" $fil
rm tmp2
