#!/usr/bin/env bash
# Configures an Nginx server to have a custom 404 page that contains the string
# Uses sed command to edit the /etc/nginx/sites-available/default file
# Ceci n'est pas une page
# Contains a custom HTTP header named X-Served-By.

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;
	add_header X-Served-By $HOSTNAME;

	location /redirect_me {
		return 301 http://google.com/;
	}

	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
