#!/usr/bin/env bash
# This script pings an IP address passed as an argument.
# 	Requirements:
#		Accepts a string as an argument
#		Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#		Ping the IP 5 times

IP=$1

if [ $#  -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi

ping -c 5 "$IP"
