#!/usr/bin/env bash
# creates the file '/var/run/myscript.pid' containing its PID
# Displays 'To infinity and beyond' indefinitely
# Displays 'I hate the kill command' when receiving a SIGTERM signal
# Displays 'Y U no love me?!' when receiving a SIGINIT signal
# Deletes the file '/var/run/myscript.pid' and terminates itself when receiving a SIGQUIT or SIGTERM signal

file=/var/run/myscript.pid
echo "$$" > $file
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$file"' SIGQUIT

i=0

while [ $i -eq 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
