#!/usr/bin/env bash
# Displays numbers from 1 to 100.
# Requirements:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number

for (( i=1; i<=100; i++ ))
do
	if (( (i % 3) == 0 && (i % 5) == 0 ))
	then
		echo "FizzBuzz"
		continue
	elif (( (i % 3) == 0 && (i % 5) != 0 ))
	then
		echo "Fizz"
		continue
	elif (( (i % 3) !=  0 && (i % 5) == 0 ))
	then
		echo "Buzz"
		continue
	else
		echo "$i"
	fi
done
