#!/usr/bin/env bash
# This script displays:
#	The content of the current directory
#	In a list format

for file in *
do
	if [ -f "$file" ]
	then
		if [[ ! $file == .* && $file == *-* ]]
		then
			name=${file#*-}
			echo "$name"
		else
			echo "$file"
		fi
	fi
done
